#!/bin/sh
#
# WARNING: REQUIRES /bin/sh
#
# - must run on /bin/sh on solaris 9
# - must run on /bin/sh on AIX 6.x
# - if you think you are a bash wizard, you probably do not understand
#   this programming language.  do not touch.
# - if you are under 40, get peer review from your elders.
#
# Perform necessary sensu setup steps
# after package is installed.
#

is_darwin()
{
  uname -v | grep "^Darwin" > /dev/null 2>&1
}

is_smartos()
{
  uname -v | grep "^joyent" > /dev/null 2>&1
}

is_aix()
{
  uname -a | grep "^AIX" > /dev/null 2>&1
}

is_freebsd()
{
  uname -v | grep "^FreeBSD" > /dev/null 2>&1
}

is_solaris()
{
  uname -a | grep "^SunOS" > /dev/null 2>&1
}

is_linux()
{
  uname -a | grep "^Linux" > /dev/null 2>&1
}

using_systemd()
{
  [ -e "/proc/1/comm" ] && grep -q "^systemd$" /proc/1/comm
}

using_upstart()
{
  [ -e "/sbin/initctl" ]
}

PROGNAME=`basename $0`

if is_freebsd; then
  ETC_DIR=/usr/local/etc
else
  ETC_DIR=/etc
fi

INSTALLER_DIR=/opt/sensu
EMBEDDED_DIR=$INSTALLER_DIR/embedded
EMBEDDED_BIN_DIR=$EMBEDDED_DIR/bin
SHARE_DIR=$EMBEDDED_DIR/share
LOG_DIR=/var/log/sensu
PID_DIR=/var/run/sensu
CONFIG_DIR=$ETC_DIR/sensu
CONFD_DIR=$CONFIG_DIR/conf.d
PLUGINS_DIR=$CONFIG_DIR/plugins
EXTENSIONS_DIR=$CONFIG_DIR/extensions
DEFAULTS_DIR=$ETC_DIR/default

LOG_FILE=$LOG_DIR/sensu-client.log
CONFIG_FILE=$CONFIG_DIR/config.json

LOG_LEVEL=info

OPTIONS="-c $CONFIG_FILE -d $CONFD_DIR -e $EXTENSIONS_DIR -l $LOG_FILE -L $LOG_LEVEL"

SENSU_PATHS=$EMBEDDED_BIN_DIR:$PATH:$PLUGINS_DIR:$HANDLERS_DIR
SENSU_GEM_PATHS=$EMBEDDED_DIR/lib/ruby/gems/2.2.0:$GEM_PATH

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

create_sensu_user_aix()
{
  # add /usr/bin/false to the list of allowed shells
  # NOTE: this is all terrible and makes kittens cry.
  # it should all be replaced by a single, idempotent command
  /usr/bin/lssec -f /etc/security/login.cfg -s usw -a shells | /usr/bin/grep "/usr/bin/false" > /dev/null
  RC=$?
  if [ "${RC}" != "0" ]; then
    SHVAL=`/usr/bin/lssec -f /etc/security/login.cfg -s usw -a shells | /usr/bin/cut -d '=' -f2`
    /usr/bin/chsec -f /etc/security/login.cfg -s usw -a shells="${SHVAL},/usr/bin/false"
  fi

  # create the system user
  mkuser pgrp="sensu" shell="/usr/bin/false" home="/opt/sensu" sensu
}

create_sensu_user_group()
{
  # create sensu group
  grep "^sensu:" /etc/group > /dev/null
  if [ "${?}" != "0" ]; then
    if is_aix; then
      mkgroup sensu
    elif is_solaris; then
      groupadd sensu
    elif is_linux; then
      groupadd -r sensu
    fi
  fi

  # create sensu user
  grep "^sensu:" /etc/passwd > /dev/null
  if [ "${?}" != "0" ]; then
    if is_aix; then
      create_sensu_user_aix
    elif is_solaris; then
      useradd -d $INSTALLER_DIR -g sensu sensu # user will be disabled by default
      passwd -N sensu # enable the user with nologin (NL)
    elif is_linux; then
      useradd -r -g sensu -d /opt/sensu -s /bin/false -c "Sensu Monitoring Framework" sensu
    fi
  fi
}

create_sensu_dirs()
{
  mkdir -p $CONFIG_DIR
  mkdir -p $CONFD_DIR
  mkdir -p $EXTENSIONS_DIR
  mkdir -p $PLUGINS_DIR
  mkdir -p $LOG_DIR
  mkdir -p $PID_DIR
  mkdir -p $DEFAULTS_DIR

  if is_solaris; then
    mkdir -p /lib/svc/manifest/site
  fi
}

create_sensu_config_example()
{
  cp $SHARE_DIR/sensu/etc/sensu/config.json.example $CONFIG_DIR/
}

chown_sensu_dirs()
{
  # Ensure all files/directories in $INSTALLER_DIR are owned by root.
  chown -Rh 0:0 $INSTALLER_DIR
  chown -R sensu:sensu $CONFIG_DIR
  chown -R sensu:sensu $LOG_DIR
  chown -R sensu:sensu $PID_DIR
}

detect_tmp_sticky_bit()
{
  LAST_BIT=`ls -ld /tmp | awk '{print substr($1,10,1)}'`
  if [ "x${LAST_BIT}" != "xt" ]; then
    echo
    echo "********************** WARNING! **********************"
    echo " Sticky bit must be set on /tmp for Sensu to function "
    echo "******************************************************"
    echo
  fi
}

create_system_services()
{
  if is_aix; then
    rmssys -s sensu-client 2>&1 > /dev/null
    mkssys -s sensu-client -p $SHARE_DIR/sensu/etc/rc.d/sensu-client -u sensu -S -n 15 -f 9 > /dev/null
  elif is_solaris; then
    cp $SHARE_DIR/sensu/lib/svc/manifest/site/sensu-client.xml /lib/svc/manifest/site/sensu-client.xml > /dev/null
  elif is_linux; then
    if using_systemd; then
      cp $SHARE_DIR/sensu/etc/systemd/system/sensu-* /etc/systemd/system
    elif using_upstart; then
      cp $SHARE_DIR/sensu/etc/init/sensu-* /etc/init
    else
      # if not systemd or upstart, we assume sysvinit
      cp $SHARE_DIR/sensu/etc/init.d/sensu-* /etc/init.d
    fi
  fi
}

create_sensu_symlinks()
{
  ln -s $INSTALLER_DIR/bin/sensu-install /usr/bin/sensu-install
}

detect_tmp_sticky_bit
create_sensu_user_group
create_sensu_dirs
create_sensu_config_example
chown_sensu_dirs
create_system_services
create_sensu_symlinks

echo "Thank you for installing Sensu!"

exit 0
EOF
