#!/bin/sh
#
# WARNING: REQUIRES /bin/sh
#
# - must run on /bin/sh on solaris 9
# - must run on /bin/sh on AIX 6.x
# - if you think you are a bash wizard, you probably do not understand
#   this programming language.  do not touch.
# - if you are under 40, get peer review from your elders.
#
# Perform necessary sensu removal steps
# after package is uninstalled.
#

is_darwin()
{
  uname -v | grep "^Darwin" > /dev/null 2>&1
}

is_smartos()
{
  uname -v | grep "^joyent" > /dev/null 2>&1
}

is_aix()
{
  uname -a | grep "^AIX" > /dev/null 2>&1
}

is_freebsd()
{
  uname -v | grep "^FreeBSD" > /dev/null 2>&1
}

is_solaris()
{
  uname -a | grep "^SunOS" > /dev/null 2>&1
}

is_linux()
{
  uname -a | grep "^Linux" > /dev/null 2>&1
}

using_systemd()
{
  [ -e "/proc/1/comm" ] && grep -q "^systemd$" /proc/1/comm
}

purge_linux_service_files()
{
  sensu_services="client server api service-init"
  for sensu_service in $sensu_services; do
    systemd_file="/etc/systemd/system/sensu-${sensu_service}.service"
    sysvinit_file="/etc/init.d/sensu-${sensu_service}"
    if [ -f $systemd_file ]; then
      rm -f $systemd_file
    fi
    if [ -f $sysvinit_file ]; then
      rm -f $sysvinit_file
    fi
  done
}

purge_sensu_services()
{
  if is_aix; then
    rmssys -s sensu-client > /dev/null 2>&1
    rmssys -s sensu-api > /dev/null 2>&1
    rmssys -s sensu-server > /dev/null 2>&1
  elif is_solaris; then
    rm -f /lib/svc/manifest/site/sensu-client.xml
  elif is_linux; then
    purge_linux_service_files
  fi
}

purge_sensu_files()
{
  if [ -d /usr/share/sensu ]; then
    rm -r /usr/share/sensu
  fi
  if [ -d /opt/sensu ]; then
    rm -r /opt/sensu
  fi
  if [ -d /var/cache/sensu ]; then
    rm -rf /var/cache/sensu
  fi
}

purge_sensu_user_group()
{
  grep "^sensu:" /etc/passwd > /dev/null
  if [ "${?}" = "0" ]; then
    if is_aix; then
      rmuser sensu > /dev/null
    elif is_solaris; then
      userdel sensu > /dev/null
    elif is_linux; then
      userdel -f sensu
    elif is_freebsd; then
      pw userdel sensu
    fi
  fi

  grep "^sensu:" /etc/group > /dev/null
  if [ "${?}" = "0" ]; then
    if is_aix; then
      rmgroup sensu > /dev/null
    elif is_solaris; then
      groupdel sensu > /dev/null
    elif is_linux; then
      groupdel sensu
    elif is_freebsd; then
      pw groupdel sensu
    fi
  fi
}

purge_sensu_symlinks()
{
  rm -f /usr/bin/sensu-install
}

purge_sensu_services
purge_sensu_files
purge_sensu_user_group
purge_sensu_symlinks

echo "Sensu has been uninstalled!"

exit 0
