#!/bin/sh
#
# WARNING: REQUIRES /bin/sh
#
# - must run on /bin/sh on solaris 9
# - must run on /bin/sh on AIX 6.x
# - if you think you are a bash wizard, you probably do not understand
#   this programming language.  do not touch.
# - if you are under 40, get peer review from your elders.
#
# Perform necessary sensu setup steps
# after package is installed.
#

is_darwin()
{
  uname -v | grep "^Darwin" > /dev/null 2>&1
}

is_smartos()
{
  uname -v | grep "^joyent" > /dev/null 2>&1
}

is_aix()
{
  uname -a | grep "^AIX" > /dev/null 2>&1
}

is_freebsd()
{
  uname -v | grep "^FreeBSD" > /dev/null 2>&1
}

is_solaris()
{
  uname -a | grep "^SunOS" > /dev/null 2>&1
}

is_linux()
{
  uname -a | grep "^Linux" > /dev/null 2>&1
}

using_systemd()
{
  [ -e "/proc/1/comm" ] && grep -q "^systemd$" /proc/1/comm
}

PROGNAME=`basename $0`

if is_freebsd; then
  ETC_DIR=/usr/local/etc
else
  ETC_DIR=/etc
fi

INSTALLER_DIR=/opt/sensu
EMBEDDED_DIR=$INSTALLER_DIR/embedded
EMBEDDED_BIN_DIR=$EMBEDDED_DIR/bin
SHARE_DIR=$EMBEDDED_DIR/share
LOG_DIR=/var/log/sensu
PID_DIR=/var/run/sensu
TMP_DIR=/var/cache/sensu
CONFIG_DIR=$ETC_DIR/sensu
CONFD_DIR=$CONFIG_DIR/conf.d
PLUGINS_DIR=$CONFIG_DIR/plugins
EXTENSIONS_DIR=$CONFIG_DIR/extensions
DEFAULTS_DIR=$ETC_DIR/default

LOG_FILE=$LOG_DIR/sensu-client.log
CONFIG_FILE=$CONFIG_DIR/config.json

LOG_LEVEL=info

OPTIONS="-c $CONFIG_FILE -d $CONFD_DIR -e $EXTENSIONS_DIR -l $LOG_FILE -L $LOG_LEVEL"

SENSU_PATHS=$EMBEDDED_BIN_DIR:$PATH:$PLUGINS_DIR:$HANDLERS_DIR
SENSU_GEM_PATHS=$EMBEDDED_DIR/lib/ruby/gems/2.2.0:$GEM_PATH

SYSV_SCRIPTS_EXIST=false

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

create_sensu_user_aix()
{
  # add /usr/bin/false to the list of allowed shells
  # NOTE: this is all terrible and makes kittens cry.
  # it should all be replaced by a single, idempotent command
  /usr/bin/lssec -f /etc/security/login.cfg -s usw -a shells | /usr/bin/grep "/usr/bin/false" > /dev/null
  RC=$?
  if [ "${RC}" != "0" ]; then
    SHVAL=`/usr/bin/lssec -f /etc/security/login.cfg -s usw -a shells | /usr/bin/cut -d '=' -f2`
    /usr/bin/chsec -f /etc/security/login.cfg -s usw -a shells="${SHVAL},/usr/bin/false"
  fi

  # create the system user
  mkuser pgrp="sensu" shell="/usr/bin/false" home="/opt/sensu" sensu
}

create_sensu_user_group()
{
  # create sensu group
  grep "^sensu:" /etc/group > /dev/null
  if [ "${?}" != "0" ]; then
    if is_aix; then
      mkgroup sensu
    elif is_solaris; then
      groupadd sensu
    elif is_freebsd; then
      pw groupadd sensu
    elif is_linux; then
      groupadd -r sensu
    fi
  fi

  # create sensu user
  grep "^sensu:" /etc/passwd > /dev/null
  if [ "${?}" != "0" ]; then
    if is_aix; then
      create_sensu_user_aix
    elif is_solaris; then
      useradd -d $INSTALLER_DIR -g sensu sensu # user will be disabled by default
      passwd -N sensu # enable the user with nologin (NL)
    elif is_freebsd; then
      pw adduser sensu -g sensu -d /nonexistent -s /usr/sbin/nologin -c "Sensu Monitoring Framework"
    elif is_linux; then
      useradd -r -g sensu -d /opt/sensu -s /bin/false -c "Sensu Monitoring Framework" sensu
    fi
  fi
}

create_sensu_dirs()
{
  mkdir -p $CONFIG_DIR
  mkdir -p $CONFD_DIR
  mkdir -p $EXTENSIONS_DIR
  mkdir -p $PLUGINS_DIR
  mkdir -p $LOG_DIR
  mkdir -p $PID_DIR
  mkdir -p $DEFAULTS_DIR
  mkdir -p $TMP_DIR

  if is_solaris; then
    mkdir -p /lib/svc/manifest/site
  fi
}

create_sensu_config_example()
{
  cp $SHARE_DIR/sensu/etc/sensu/config.json.example $CONFIG_DIR
}

create_sensu_default()
{
  if [ ! -d "${ETC_DIR}/default" ]; then
    mkdir $ETC_DIR/default
  fi
  cp $SHARE_DIR/sensu/etc/default/sensu $ETC_DIR/default/sensu
}

create_sensu_logrotated_config()
{
  if [ -d "${ETC_DIR}/logrotate.d" ]; then
    cp $SHARE_DIR/sensu/etc/logrotate.d/sensu $ETC_DIR/logrotate.d
  fi
}

chown_sensu_dirs()
{
  # Ensure all files/directories in $INSTALLER_DIR are owned by root.
  chown -Rh 0:0 $INSTALLER_DIR
  chown -R sensu:sensu $CONFIG_DIR
  chown -R sensu:sensu $LOG_DIR
  chown -R sensu:sensu $PID_DIR
  chown -R sensu:sensu $TMP_DIR
}

create_system_services()
{
  if is_aix; then
    rmssys -s sensu-client 2>&1 > /dev/null
    mkssys -s sensu-client -p $SHARE_DIR/sensu/etc/rc.d/sensu-client -u sensu -S -n 15 -f 9 > /dev/null
  elif is_solaris; then
    cp $SHARE_DIR/sensu/lib/svc/manifest/site/sensu-client.xml /lib/svc/manifest/site/sensu-client.xml > /dev/null
  elif is_linux; then
    if using_systemd; then
      echo -n "systemd detected, "
      sysv_init_test
      if [ "x${SYSV_EXISTS}" = "xtrue" ]; then
        echo "but sysv init scripts are present so we'll use those instead"
        install_sysv_scripts
      else
        echo "installing unit files"
        install_systemd_units
      fi
    else
      # if not systemd, we assume sysvinit
      echo "systemd not detected, installing sysv init scripts"
      install_sysv_scripts
    fi
  fi
}

install_systemd_units()
{
  for service in api client server
  do
    echo "installing sensu-${service}.service systemd unit"
    cp "${SHARE_DIR}/sensu/etc/systemd/system/sensu-${service}.service" "/lib/systemd/system/sensu-${service}.service"
  done
}

install_sysv_scripts()
{
  for service in api client server service-init
  do
    echo "Installing sensu-${service} sysv init script"
    cp "${SHARE_DIR}/sensu/etc/init.d/sensu-${service}" /etc/init.d
    chmod 755 "/etc/init.d/sensu-${service}"
  done
}

create_sensu_symlinks()
{
  ln -s $INSTALLER_DIR/bin/sensu-install /usr/bin/sensu-install
}

sysv_init_test()
{
  for service in api client server
  do
    if [ -f "/etc/init.d/sensu-${service}" ]; then
      SYSV_EXISTS=true
    fi
  done
}

create_sensu_user_group
create_sensu_dirs
create_sensu_config_example
create_sensu_default
create_sensu_logrotated_config
chown_sensu_dirs
create_system_services
create_sensu_symlinks

echo "Thank you for installing Sensu!"

exit 0
EOF
