#!/bin/sh
#
# WARNING: REQUIRES /bin/sh
#
# - must run on /bin/sh on solaris 9
# - must run on /bin/sh on AIX 6.x
# - if you think you are a bash wizard, you probably do not understand
#   this programming language.  do not touch.
# - if you are under 40, get peer review from your elders.
#
#
# Perform necessary sensu setup steps
# prior to installing package.
#

is_darwin()
{
  uname -v | grep "^Darwin" > /dev/null 2>&1
}

is_smartos()
{
  uname -v | grep "^joyent" > /dev/null 2>&1
}

is_aix()
{
  uname -a | grep "^AIX" > /dev/null 2>&1
}

is_freebsd()
{
  uname -v | grep "^FreeBSD" > /dev/null 2>&1
}

is_solaris()
{
  uname -a | grep "^SunOS" > /dev/null 2>&1
}

is_linux()
{
  uname -a | grep "^Linux" > /dev/null 2>&1
}

using_systemd()
{
  [ -e "/proc/1/comm" ] && grep -q "^systemd$" /proc/1/comm
}

using_upstart()
{
  [ -e "/sbin/initctl" ]
}

PROGNAME=`basename $0`

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

stop_sensu_services()
{
  if is_aix; then
    stopsrc -s sensu-client > /dev/null 2>&1
  elif is_solaris; then
    svcadm disable sensu-client > /dev/null 2>&1
  elif is_linux; then
    sensu_services="client server api"
    for sensu_service in $sensu_services; do
      if using_systemd; then
        systemctl stop "sensu-${sensu_service}" || true
      elif using_upstart; then
        service "sensu-${sensu_service}" stop || true
      else
        /etc/init.d/sensu-$sensu_service stop || true
      fi
    done
  fi
}

stop_sensu_services

# wait for services to stop
sleep 6

exit 0
EOF
