#!/bin/sh
#
# WARNING: REQUIRES /bin/sh
#
# - must run on /bin/sh on solaris 9
# - must run on /bin/sh on AIX 6.x
# - if you think you are a bash wizard, you probably do not understand
#   this programming language.  do not touch.
# - if you are under 40, get peer review from your elders.
#

is_darwin()
{
  uname -v | grep "^Darwin" > /dev/null 2>&1
}

is_smartos()
{
  uname -v | grep "^joyent" > /dev/null 2>&1
}

is_aix()
{
  uname -a | grep "^AIX" > /dev/null 2>&1
}

is_freebsd()
{
  uname -v | grep "^FreeBSD" > /dev/null 2>&1
}

sensu_service=sensu-client

EMBEDDED_RUBY=true
ETC_DIR=

if is_freebsd; then
  ETC_DIR=/usr/local/etc
else
  ETC_DIR=/etc
fi

INSTALLER_DIR=/opt/sensu
CONFIG_DIR=$ETC_DIR/sensu
CONFIG_FILE=$CONFIG_DIR/config.json
CONFD_DIR=$CONFIG_DIR/conf.d
EXTENSION_DIR=$CONFIG_DIR/extensions
PLUGINS_DIR=$CONFIG_DIR/plugins
LOG_DIR=/var/log/sensu
LOG_FILE=$LOG_DIR/$sensu_service.log
LOG_LEVEL=debug
PID_DIR=/var/run/sensu
PID_FILE=$PID_DIR/$sensu_service.pid
USER=sensu

if [ -f $ETC_DIR/default/sensu ]; then
    . $ETC_DIR/default/sensu
fi

cd $INSTALLER_DIR

exec="exec $INSTALLER_DIR/bin/$sensu_service"

options="-c $CONFIG_FILE -d $CONFD_DIR -e $EXTENSION_DIR -p $PID_FILE -l $LOG_FILE -L $LOG_LEVEL $OPTIONS"

set_sensu_paths()
{
    if [ "$EMBEDDED_RUBY" = "true" ]; then
        PATH=$INSTALLER_DIR/embedded/bin:$PATH:$PLUGINS_DIR
        GEM_PATH=$INSTALLER_DIR/embedded/lib/ruby/gems/2.3.0:$GEM_PATH
        export PATH
        export GEM_PATH
    else
        PATH=$PATH:$PLUGINS_DIR:$HANDLERS_DIR
        export PATH
    fi
}

ensure_dir()
{
    if [ ! -d $1 ]; then
        mkdir -p $1
        chown -R $2 $1
        chmod 755 $1
    fi
}

set_sensu_paths
ensure_dir $PID_DIR $USER
ensure_dir $LOG_DIR $USER
$exec $options
